import React from "react";
import { Meta, StoryFn } from "@storybook/react";
import {AutoGeneratedDefaultInputProps} from "../components/Input/AutoGeneratedDefaultInput";
import AutoGeneratedDefaultInput from "../components/Input/AutoGeneratedDefaultInput/AutoGeneratedDefaultInput";


export default {
    title: "Components/AutoGeneratedDefaultInput",
    component: AutoGeneratedDefaultInput,
    argTypes: {
        value: { control: "text" },
        proSetting: { control: "boolean" },
        description: { control: "text" },
        onChange: { action: "changed" },
    },
} as Meta<typeof AutoGeneratedDefaultInput>;

const Template: StoryFn<AutoGeneratedDefaultInputProps> = (args) => <AutoGeneratedDefaultInput {...args} />;

export const Default = Template.bind({});
Default.args = {
    value: "",
};

export const WithValue = Template.bind({});
WithValue.args = {
    value: "ABC12345",
};

export const WithProTag = Template.bind({});
WithProTag.args = {
    value: "PRO-KEY-1234",
    proSetting: true,
};

export const WithDescription = Template.bind({});
WithDescription.args = {
    value: "KEY-EXAMPLE-5678",
    description: "This is an autogenerated key for authentication purposes.",
};

export const EmptyState = Template.bind({});
EmptyState.args = {
    value: "",
};
